# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/spindle_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(212, 580)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.checkBoxS1 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS1.setFont(font)
        self.checkBoxS1.setChecked(True)
        self.checkBoxS1.setObjectName("checkBoxS1")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.setExclusive(False)
        self.buttonGroup.addButton(self.checkBoxS1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBoxS1)
        self.checkBoxS2 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS2.setFont(font)
        self.checkBoxS2.setChecked(True)
        self.checkBoxS2.setObjectName("checkBoxS2")
        self.buttonGroup.addButton(self.checkBoxS2)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBoxS2)
        self.checkBoxS3 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS3.setFont(font)
        self.checkBoxS3.setChecked(True)
        self.checkBoxS3.setObjectName("checkBoxS3")
        self.buttonGroup.addButton(self.checkBoxS3)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBoxS3)
        self.checkBoxS4 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS4.setFont(font)
        self.checkBoxS4.setChecked(True)
        self.checkBoxS4.setObjectName("checkBoxS4")
        self.buttonGroup.addButton(self.checkBoxS4)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBoxS4)
        self.checkBoxS5 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS5.setFont(font)
        self.checkBoxS5.setChecked(True)
        self.checkBoxS5.setObjectName("checkBoxS5")
        self.buttonGroup.addButton(self.checkBoxS5)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBoxS5)
        self.checkBoxS6 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS6.setFont(font)
        self.checkBoxS6.setChecked(True)
        self.checkBoxS6.setObjectName("checkBoxS6")
        self.buttonGroup.addButton(self.checkBoxS6)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBoxS6)
        self.checkBoxS7 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS7.setFont(font)
        self.checkBoxS7.setChecked(True)
        self.checkBoxS7.setObjectName("checkBoxS7")
        self.buttonGroup.addButton(self.checkBoxS7)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBoxS7)
        self.checkBoxS8 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS8.setFont(font)
        self.checkBoxS8.setChecked(True)
        self.checkBoxS8.setObjectName("checkBoxS8")
        self.buttonGroup.addButton(self.checkBoxS8)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBoxS8)
        self.checkBoxS9 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS9.setFont(font)
        self.checkBoxS9.setChecked(True)
        self.checkBoxS9.setObjectName("checkBoxS9")
        self.buttonGroup.addButton(self.checkBoxS9)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkBoxS9)
        self.checkBoxS10 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS10.setFont(font)
        self.checkBoxS10.setChecked(True)
        self.checkBoxS10.setObjectName("checkBoxS10")
        self.buttonGroup.addButton(self.checkBoxS10)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkBoxS10)
        self.checkBoxS11 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS11.setFont(font)
        self.checkBoxS11.setChecked(True)
        self.checkBoxS11.setObjectName("checkBoxS11")
        self.buttonGroup.addButton(self.checkBoxS11)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.checkBoxS11)
        self.checkBoxS12 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS12.setFont(font)
        self.checkBoxS12.setChecked(True)
        self.checkBoxS12.setObjectName("checkBoxS12")
        self.buttonGroup.addButton(self.checkBoxS12)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkBoxS12)
        self.checkBoxS13 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS13.setFont(font)
        self.checkBoxS13.setChecked(True)
        self.checkBoxS13.setObjectName("checkBoxS13")
        self.buttonGroup.addButton(self.checkBoxS13)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.checkBoxS13)
        self.checkBoxS14 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS14.setFont(font)
        self.checkBoxS14.setChecked(True)
        self.checkBoxS14.setObjectName("checkBoxS14")
        self.buttonGroup.addButton(self.checkBoxS14)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.checkBoxS14)
        self.checkBoxS15 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS15.setFont(font)
        self.checkBoxS15.setChecked(True)
        self.checkBoxS15.setObjectName("checkBoxS15")
        self.buttonGroup.addButton(self.checkBoxS15)
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.checkBoxS15)
        self.checkBoxS16 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS16.setFont(font)
        self.checkBoxS16.setChecked(True)
        self.checkBoxS16.setObjectName("checkBoxS16")
        self.buttonGroup.addButton(self.checkBoxS16)
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.checkBoxS16)
        self.checkBoxS17 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS17.setFont(font)
        self.checkBoxS17.setChecked(True)
        self.checkBoxS17.setObjectName("checkBoxS17")
        self.buttonGroup.addButton(self.checkBoxS17)
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.checkBoxS17)
        self.checkBoxS18 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS18.setFont(font)
        self.checkBoxS18.setChecked(True)
        self.checkBoxS18.setObjectName("checkBoxS18")
        self.buttonGroup.addButton(self.checkBoxS18)
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.checkBoxS18)
        self.checkBoxS19 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS19.setFont(font)
        self.checkBoxS19.setChecked(True)
        self.checkBoxS19.setObjectName("checkBoxS19")
        self.buttonGroup.addButton(self.checkBoxS19)
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.checkBoxS19)
        self.checkBoxS20 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS20.setFont(font)
        self.checkBoxS20.setChecked(True)
        self.checkBoxS20.setObjectName("checkBoxS20")
        self.buttonGroup.addButton(self.checkBoxS20)
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.checkBoxS20)
        self.checkBoxS21 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS21.setFont(font)
        self.checkBoxS21.setChecked(True)
        self.checkBoxS21.setObjectName("checkBoxS21")
        self.buttonGroup.addButton(self.checkBoxS21)
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.checkBoxS21)
        self.checkBoxS22 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxS22.setFont(font)
        self.checkBoxS22.setChecked(True)
        self.checkBoxS22.setObjectName("checkBoxS22")
        self.buttonGroup.addButton(self.checkBoxS22)
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.checkBoxS22)
        self.pushButtonSelectReverse = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelectReverse.sizePolicy().hasHeightForWidth())
        self.pushButtonSelectReverse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButtonSelectReverse.setFont(font)
        self.pushButtonSelectReverse.setObjectName("pushButtonSelectReverse")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.pushButtonSelectReverse)
        self.pushButtonSelectAll = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelectAll.sizePolicy().hasHeightForWidth())
        self.pushButtonSelectAll.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButtonSelectAll.setFont(font)
        self.pushButtonSelectAll.setObjectName("pushButtonSelectAll")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.pushButtonSelectAll)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.dateEditStart = QtWidgets.QDateEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEditStart.sizePolicy().hasHeightForWidth())
        self.dateEditStart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.dateEditStart.setFont(font)
        self.dateEditStart.setObjectName("dateEditStart")
        self.verticalLayout_2.addWidget(self.dateEditStart)
        self.label_2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.dateEditEnd = QtWidgets.QDateEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEditEnd.sizePolicy().hasHeightForWidth())
        self.dateEditEnd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.dateEditEnd.setFont(font)
        self.dateEditEnd.setObjectName("dateEditEnd")
        self.verticalLayout_2.addWidget(self.dateEditEnd)
        self.checkBoxAllData = QtWidgets.QCheckBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxAllData.sizePolicy().hasHeightForWidth())
        self.checkBoxAllData.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBoxAllData.setFont(font)
        self.checkBoxAllData.setChecked(True)
        self.checkBoxAllData.setObjectName("checkBoxAllData")
        self.verticalLayout_2.addWidget(self.checkBoxAllData)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.checkBoxAllData.clicked['bool'].connect(self.dateEditEnd.setDisabled)
        self.checkBoxAllData.clicked['bool'].connect(self.dateEditStart.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.dateEditStart, self.checkBoxS22)
        Dialog.setTabOrder(self.checkBoxS22, self.checkBoxS21)
        Dialog.setTabOrder(self.checkBoxS21, self.checkBoxS20)
        Dialog.setTabOrder(self.checkBoxS20, self.checkBoxS19)
        Dialog.setTabOrder(self.checkBoxS19, self.checkBoxS18)
        Dialog.setTabOrder(self.checkBoxS18, self.checkBoxS17)
        Dialog.setTabOrder(self.checkBoxS17, self.checkBoxS16)
        Dialog.setTabOrder(self.checkBoxS16, self.checkBoxS15)
        Dialog.setTabOrder(self.checkBoxS15, self.checkBoxS14)
        Dialog.setTabOrder(self.checkBoxS14, self.checkBoxS13)
        Dialog.setTabOrder(self.checkBoxS13, self.checkBoxS12)
        Dialog.setTabOrder(self.checkBoxS12, self.checkBoxS11)
        Dialog.setTabOrder(self.checkBoxS11, self.checkBoxS10)
        Dialog.setTabOrder(self.checkBoxS10, self.checkBoxS9)
        Dialog.setTabOrder(self.checkBoxS9, self.checkBoxS8)
        Dialog.setTabOrder(self.checkBoxS8, self.checkBoxS7)
        Dialog.setTabOrder(self.checkBoxS7, self.checkBoxS6)
        Dialog.setTabOrder(self.checkBoxS6, self.checkBoxS5)
        Dialog.setTabOrder(self.checkBoxS5, self.checkBoxS4)
        Dialog.setTabOrder(self.checkBoxS4, self.checkBoxS3)
        Dialog.setTabOrder(self.checkBoxS3, self.checkBoxS2)
        Dialog.setTabOrder(self.checkBoxS2, self.checkBoxS1)
        Dialog.setTabOrder(self.checkBoxS1, self.dateEditEnd)
        Dialog.setTabOrder(self.dateEditEnd, self.pushButtonSelectReverse)
        Dialog.setTabOrder(self.pushButtonSelectReverse, self.checkBoxAllData)
        Dialog.setTabOrder(self.checkBoxAllData, self.pushButtonSelectAll)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "拧紧枪选择"))
        self.checkBoxS1.setText(_translate("Dialog", "1号枪"))
        self.checkBoxS2.setText(_translate("Dialog", "2号枪"))
        self.checkBoxS3.setText(_translate("Dialog", "3号枪"))
        self.checkBoxS4.setText(_translate("Dialog", "4号枪"))
        self.checkBoxS5.setText(_translate("Dialog", "5号枪"))
        self.checkBoxS6.setText(_translate("Dialog", "6号枪"))
        self.checkBoxS7.setText(_translate("Dialog", "7号枪"))
        self.checkBoxS8.setText(_translate("Dialog", "8号枪"))
        self.checkBoxS9.setText(_translate("Dialog", "9号枪"))
        self.checkBoxS10.setText(_translate("Dialog", "10号枪"))
        self.checkBoxS11.setText(_translate("Dialog", "11号枪"))
        self.checkBoxS12.setText(_translate("Dialog", "12号枪"))
        self.checkBoxS13.setText(_translate("Dialog", "13号枪"))
        self.checkBoxS14.setText(_translate("Dialog", "14号枪"))
        self.checkBoxS15.setText(_translate("Dialog", "15号枪"))
        self.checkBoxS16.setText(_translate("Dialog", "16号枪"))
        self.checkBoxS17.setText(_translate("Dialog", "17号枪"))
        self.checkBoxS18.setText(_translate("Dialog", "18号枪"))
        self.checkBoxS19.setText(_translate("Dialog", "19号枪"))
        self.checkBoxS20.setText(_translate("Dialog", "20号枪"))
        self.checkBoxS21.setText(_translate("Dialog", "21号枪"))
        self.checkBoxS22.setText(_translate("Dialog", "22号枪"))
        self.pushButtonSelectReverse.setText(_translate("Dialog", "反选"))
        self.pushButtonSelectAll.setText(_translate("Dialog", "全选"))
        self.label.setText(_translate("Dialog", "开始日期"))
        self.dateEditStart.setDisplayFormat(_translate("Dialog", "yyyy/M/d"))
        self.label_2.setText(_translate("Dialog", "结束日期"))
        self.dateEditEnd.setDisplayFormat(_translate("Dialog", "yyyy/M/d"))
        self.checkBoxAllData.setText(_translate("Dialog", "读取最新数据"))

