# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/spcwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SPCWindow(object):
    def setupUi(self, SPCWindow):
        SPCWindow.setObjectName("SPCWindow")
        SPCWindow.resize(807, 523)
        self.centralwidget = QtWidgets.QWidget(SPCWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.figure_layout = QtWidgets.QVBoxLayout()
        self.figure_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.figure_layout.setObjectName("figure_layout")
        self.verticalLayout_2.addLayout(self.figure_layout)
        self.label_type = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_type.sizePolicy().hasHeightForWidth())
        self.label_type.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_type.setFont(font)
        self.label_type.setObjectName("label_type")
        self.verticalLayout_2.addWidget(self.label_type)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.slider_spc = QtWidgets.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.slider_spc.setFont(font)
        self.slider_spc.setMaximum(1000000)
        self.slider_spc.setOrientation(QtCore.Qt.Horizontal)
        self.slider_spc.setObjectName("slider_spc")
        self.horizontalLayout.addWidget(self.slider_spc)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.spin_range = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.spin_range.setFont(font)
        self.spin_range.setMinimum(20)
        self.spin_range.setMaximum(25)
        self.spin_range.setProperty("value", 23)
        self.spin_range.setObjectName("spin_range")
        self.horizontalLayout_2.addWidget(self.spin_range)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spin_spc = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.spin_spc.setFont(font)
        self.spin_spc.setMaximum(1000000)
        self.spin_spc.setObjectName("spin_spc")
        self.horizontalLayout_2.addWidget(self.spin_spc)
        self.line = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.total_part = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_part.sizePolicy().hasHeightForWidth())
        self.total_part.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.total_part.setFont(font)
        self.total_part.setObjectName("total_part")
        self.horizontalLayout_2.addWidget(self.total_part)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.button_spc = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.button_spc.setFont(font)
        self.button_spc.setObjectName("button_spc")
        self.horizontalLayout_2.addWidget(self.button_spc)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        SPCWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SPCWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 17))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        SPCWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SPCWindow)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        SPCWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SPCWindow)
        self.slider_spc.sliderMoved['int'].connect(self.spin_spc.setValue)
        self.spin_spc.valueChanged['int'].connect(self.button_spc.click)
        QtCore.QMetaObject.connectSlotsByName(SPCWindow)

    def retranslateUi(self, SPCWindow):
        _translate = QtCore.QCoreApplication.translate
        SPCWindow.setWindowTitle(_translate("SPCWindow", "SPC图"))
        self.label_type.setText(_translate("SPCWindow", "正常"))
        self.label_2.setText(_translate("SPCWindow", "SPC组数设置"))
        self.label_4.setText(_translate("SPCWindow", "分析长度："))
        self.label.setText(_translate("SPCWindow", "当前组数："))
        self.label_3.setText(_translate("SPCWindow", "总组数："))
        self.total_part.setText(_translate("SPCWindow", "NaT"))
        self.button_spc.setText(_translate("SPCWindow", "刷新"))

