# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/welcome.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(393, 453)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 4, 0, 1, 2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 1, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout.addWidget(self.plainTextEdit_2, 1, 1, 1, 1)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_3.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_3.setSizePolicy(sizePolicy)
        self.plainTextEdit_3.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhExclusiveInputMask|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhLowercaseOnly|QtCore.Qt.ImhUppercaseOnly|QtCore.Qt.ImhUrlCharactersOnly)
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout.addWidget(self.plainTextEdit_3, 2, 1, 1, 1)
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_4.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_4.setSizePolicy(sizePolicy)
        self.plainTextEdit_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.gridLayout.addWidget(self.plainTextEdit_4, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 393, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBar.sizePolicy().hasHeightForWidth())
        self.menuBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuFile.sizePolicy().hasHeightForWidth())
        self.menuFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuAccessProcess = QtWidgets.QMenu(self.menuFile)
        self.menuAccessProcess.setGeometry(QtCore.QRect(533, 99, 169, 126))
        self.menuAccessProcess.setObjectName("menuAccessProcess")
        self.menuMicrosoft_SQL_Server = QtWidgets.QMenu(self.menuFile)
        self.menuMicrosoft_SQL_Server.setObjectName("menuMicrosoft_SQL_Server")
        self.menuSetting = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.menuSetting.setFont(font)
        self.menuSetting.setObjectName("menuSetting")
        self.menuChangeVarities = QtWidgets.QMenu(self.menuSetting)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.menuChangeVarities.setFont(font)
        self.menuChangeVarities.setObjectName("menuChangeVarities")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.actionPartNum = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.actionPartNum.setFont(font)
        self.actionPartNum.setObjectName("actionPartNum")
        self.actionDefaultReadTime = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.actionDefaultReadTime.setFont(font)
        self.actionDefaultReadTime.setObjectName("actionDefaultReadTime")
        self.actionReverseTime = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.actionReverseTime.setFont(font)
        self.actionReverseTime.setObjectName("actionReverseTime")
        self.actionOpenComp = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.actionOpenComp.setFont(font)
        self.actionOpenComp.setObjectName("actionOpenComp")
        self.actionSpindleFatigue = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.actionSpindleFatigue.setFont(font)
        self.actionSpindleFatigue.setObjectName("actionSpindleFatigue")
        self.actionOpenMssql = QtWidgets.QAction(MainWindow)
        self.actionOpenMssql.setObjectName("actionOpenMssql")
        self.actionOpenCompMssql = QtWidgets.QAction(MainWindow)
        self.actionOpenCompMssql.setObjectName("actionOpenCompMssql")
        self.actionFatigueMssql = QtWidgets.QAction(MainWindow)
        self.actionFatigueMssql.setObjectName("actionFatigueMssql")
        self.menuAccessProcess.addAction(self.actionOpen)
        self.menuAccessProcess.addAction(self.actionOpenComp)
        self.menuAccessProcess.addAction(self.actionSpindleFatigue)
        self.menuMicrosoft_SQL_Server.addAction(self.actionOpenMssql)
        self.menuMicrosoft_SQL_Server.addAction(self.actionOpenCompMssql)
        self.menuMicrosoft_SQL_Server.addAction(self.actionFatigueMssql)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuAccessProcess.menuAction())
        self.menuFile.addAction(self.menuMicrosoft_SQL_Server.menuAction())
        self.menuFile.addAction(self.actionExit)
        self.menuChangeVarities.addSeparator()
        self.menuChangeVarities.addAction(self.actionPartNum)
        self.menuChangeVarities.addAction(self.actionReverseTime)
        self.menuChangeVarities.addAction(self.actionDefaultReadTime)
        self.menuSetting.addAction(self.menuChangeVarities.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.actionExit.triggered.connect(MainWindow.close)
        self.pushButton.clicked.connect(self.actionOpen.trigger)
        self.pushButton_2.clicked.connect(self.actionOpenComp.trigger)
        self.pushButton_3.clicked.connect(self.actionSpindleFatigue.trigger)
        self.pushButton_4.clicked.connect(MainWindow.close)
        self.pushButton_7.clicked.connect(self.actionOpenMssql.trigger)
        self.pushButton_6.clicked.connect(self.actionOpenCompMssql.trigger)
        self.pushButton_5.clicked.connect(self.actionFatigueMssql.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据库处理程序"))
        self.label.setText(_translate("MainWindow", "欢迎"))
        self.pushButton.setText(_translate("MainWindow", "单拧紧枪数据分析"))
        self.pushButton_2.setText(_translate("MainWindow", "多拧紧枪数据分析"))
        self.pushButton_3.setText(_translate("MainWindow", "拧紧枪疲劳监控"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Access"))
        self.pushButton_7.setText(_translate("MainWindow", "单拧紧枪数据分析"))
        self.pushButton_6.setText(_translate("MainWindow", "多拧紧枪数据分析"))
        self.pushButton_5.setText(_translate("MainWindow", "拧紧枪疲劳监控"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "SQL Server"))
        self.label_5.setText(_translate("MainWindow", "表名"))
        self.label_2.setText(_translate("MainWindow", "服务器名"))
        self.label_4.setText(_translate("MainWindow", "密码"))
        self.label_3.setText(_translate("MainWindow", "用户名"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.pushButton_4.setText(_translate("MainWindow", "退出"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menuAccessProcess.setTitle(_translate("MainWindow", "Access数据库处理"))
        self.menuMicrosoft_SQL_Server.setTitle(_translate("MainWindow", "Microsoft SQL Server"))
        self.menuSetting.setTitle(_translate("MainWindow", "设置"))
        self.menuChangeVarities.setTitle(_translate("MainWindow", "调整变量"))
        self.actionOpen.setText(_translate("MainWindow", "单拧紧枪分析"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionPartNum.setText(_translate("MainWindow", "分组数目"))
        self.actionDefaultReadTime.setText(_translate("MainWindow", "中断时间"))
        self.actionReverseTime.setText(_translate("MainWindow", "默认回溯月数"))
        self.actionOpenComp.setText(_translate("MainWindow", "多拧紧枪分析"))
        self.actionSpindleFatigue.setText(_translate("MainWindow", "疲劳分析"))
        self.actionOpenMssql.setText(_translate("MainWindow", "单拧紧枪分析"))
        self.actionOpenCompMssql.setText(_translate("MainWindow", "多拧紧枪分析"))
        self.actionFatigueMssql.setText(_translate("MainWindow", "疲劳监控"))

